--------------------------------------------------------
--  File created - Friday-September-06-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence DOGADJAJ_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "KONSULTACIJE"."DOGADJAJ_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 281 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence KALENDAR_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "KONSULTACIJE"."KALENDAR_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence KORISNICKI_NALOG_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "KONSULTACIJE"."KORISNICKI_NALOG_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 301 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence NASTAVNIK_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "KONSULTACIJE"."NASTAVNIK_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence PREDMET_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "KONSULTACIJE"."PREDMET_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence PRILOG_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "KONSULTACIJE"."PRILOG_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 81 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence PRILOG_SEQ1
--------------------------------------------------------

   CREATE SEQUENCE  "KONSULTACIJE"."PRILOG_SEQ1"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ROLA_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "KONSULTACIJE"."ROLA_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SKOLSKA_GODINA_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "KONSULTACIJE"."SKOLSKA_GODINA_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence TIP_DOGADJAJA_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "KONSULTACIJE"."TIP_DOGADJAJA_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table DOGADJAJ
--------------------------------------------------------

  CREATE TABLE "KONSULTACIJE"."DOGADJAJ" 
   (	"ID_KALENDARA" NUMBER, 
	"ID_DOGADJAJA" NUMBER, 
	"DATUM_I_VREME_POCETKA" DATE, 
	"DATUM_I_VREME_ZAVRSETKA" DATE, 
	"MESTO_ODRZAVANJA" VARCHAR2(50 BYTE), 
	"ID_TIPA_DOGADJAJA" NUMBER, 
	"NIVO" VARCHAR2(20 BYTE), 
	"ULOGA" VARCHAR2(50 BYTE), 
	"KANDIDAT" VARCHAR2(50 BYTE), 
	"TEMA" VARCHAR2(50 BYTE), 
	"KAPACITET" NUMBER, 
	"BROJ_ZAKAZANIH" NUMBER, 
	"ULOGA_NASTAVE" VARCHAR2(20 BYTE), 
	"ID_PREDMETA" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table KALENDAR
--------------------------------------------------------

  CREATE TABLE "KONSULTACIJE"."KALENDAR" 
   (	"ID_KALENDARA" NUMBER, 
	"ID_SKOLSKE_GODINE" NUMBER, 
	"JMBG_NASTAVNIKA" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table KORISNICKI_NALOG
--------------------------------------------------------

  CREATE TABLE "KONSULTACIJE"."KORISNICKI_NALOG" 
   (	"ID_KOR_NAL" NUMBER, 
	"KORISNICKO_IME" VARCHAR2(30 BYTE), 
	"LOZINKA" VARCHAR2(60 BYTE), 
	"JMBG_NASTAVNIKA" VARCHAR2(13 BYTE), 
	"BROJ_INDEKSA_STUDENTA" VARCHAR2(20 BYTE), 
	"CREATED_AT" DATE, 
	"CREATED_BY" NUMBER, 
	"UPDATED_AT" DATE, 
	"UPDATED_BY" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table KORISNICKI_NALOG_ROLA
--------------------------------------------------------

  CREATE TABLE "KONSULTACIJE"."KORISNICKI_NALOG_ROLA" 
   (	"KORISNICKI_NALOG_ID" NUMBER, 
	"ROLA_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table NASTAVNIK
--------------------------------------------------------

  CREATE TABLE "KONSULTACIJE"."NASTAVNIK" 
   (	"JMBG" VARCHAR2(13 BYTE), 
	"IME" VARCHAR2(20 BYTE), 
	"PREZIME" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"BROJ_TELEFONA" VARCHAR2(20 BYTE), 
	"KABINET" VARCHAR2(20 BYTE), 
	"SLIKA" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table POKRIVENOST_NASTAVE
--------------------------------------------------------

  CREATE TABLE "KONSULTACIJE"."POKRIVENOST_NASTAVE" 
   (	"JMBG_NASTAVNIKA" VARCHAR2(13 BYTE), 
	"ID_PREDMETA" NUMBER, 
	"ULOGA" VARCHAR2(20 BYTE), 
	"ID_SKOLSKE_GODINE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PREDMET
--------------------------------------------------------

  CREATE TABLE "KONSULTACIJE"."PREDMET" 
   (	"ID_PREDMETA" NUMBER, 
	"NAZIV" VARCHAR2(100 BYTE), 
	"ESPB_BODOVI" NUMBER, 
	"GODINA_STUDIJA" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PRILOG
--------------------------------------------------------

  CREATE TABLE "KONSULTACIJE"."PRILOG" 
   (	"ID_PRILOGA" NUMBER, 
	"NAZIV" VARCHAR2(20 BYTE), 
	"ID_DOGADJAJA" NUMBER, 
	"ID_KALENDARA" NUMBER, 
	"BROJ_INDEKSA_STUDENTA" VARCHAR2(20 BYTE), 
	"LOKACIJA" BLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("LOKACIJA") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table ROLA
--------------------------------------------------------

  CREATE TABLE "KONSULTACIJE"."ROLA" 
   (	"ID_ROLE" NUMBER, 
	"NAZIV_ROLE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SKOLSKA_GODINA
--------------------------------------------------------

  CREATE TABLE "KONSULTACIJE"."SKOLSKA_GODINA" 
   (	"ID_SKOLSKE_GODINE" NUMBER, 
	"SKOLSKA_GODINA" VARCHAR2(20 BYTE), 
	"SEMESTAR" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table STUDENT
--------------------------------------------------------

  CREATE TABLE "KONSULTACIJE"."STUDENT" 
   (	"BROJ_INDEKSA" VARCHAR2(10 BYTE), 
	"IME" VARCHAR2(20 BYTE), 
	"PREZIME" VARCHAR2(20 BYTE), 
	"GODINA_UPISA" NUMBER(4,0), 
	"SMER" VARCHAR2(100 BYTE), 
	"BROJ_TELEFONA" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table STUDENT_KONSULTACIJE
--------------------------------------------------------

  CREATE TABLE "KONSULTACIJE"."STUDENT_KONSULTACIJE" 
   (	"ID_KALENDARA" NUMBER, 
	"ID_DOGADJAJA" NUMBER, 
	"BROJ_INDEKSA_STUDENTA" VARCHAR2(20 BYTE), 
	"STATUS" VARCHAR2(200 BYTE), 
	"NASLOV" VARCHAR2(200 BYTE), 
	"OPIS" VARCHAR2(1000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TIP_DOGADJAJA
--------------------------------------------------------

  CREATE TABLE "KONSULTACIJE"."TIP_DOGADJAJA" 
   (	"ID_TIPA_DOGADJAJA" NUMBER, 
	"NAZIV_TIPA_DOGADJAJA" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into KONSULTACIJE.DOGADJAJ
SET DEFINE OFF;
REM INSERTING into KONSULTACIJE.KALENDAR
SET DEFINE OFF;
REM INSERTING into KONSULTACIJE.KORISNICKI_NALOG
SET DEFINE OFF;
Insert into KONSULTACIJE.KORISNICKI_NALOG (ID_KOR_NAL,KORISNICKO_IME,LOZINKA,JMBG_NASTAVNIKA,BROJ_INDEKSA_STUDENTA,CREATED_AT,CREATED_BY,UPDATED_AT,UPDATED_BY) values (285,'aass','$2a$10$E.vXkY1qkxrqTSJCSsyl8e8w4dGF8yk9q7Ie3s/1d1kwxdnHHokRS',null,null,to_date('06-SEP-19','DD-MON-RR'),null,to_date('06-SEP-19','DD-MON-RR'),null);
Insert into KONSULTACIJE.KORISNICKI_NALOG (ID_KOR_NAL,KORISNICKO_IME,LOZINKA,JMBG_NASTAVNIKA,BROJ_INDEKSA_STUDENTA,CREATED_AT,CREATED_BY,UPDATED_AT,UPDATED_BY) values (286,'aasss','$2a$10$GHtlr/i7K7b1FU1bCqUXyuQwSdIrTg3QVtGEyGe1x8dcHkLoXcTSK',null,null,to_date('06-SEP-19','DD-MON-RR'),285,to_date('06-SEP-19','DD-MON-RR'),285);
Insert into KONSULTACIJE.KORISNICKI_NALOG (ID_KOR_NAL,KORISNICKO_IME,LOZINKA,JMBG_NASTAVNIKA,BROJ_INDEKSA_STUDENTA,CREATED_AT,CREATED_BY,UPDATED_AT,UPDATED_BY) values (284,'nnn','$2a$10$bWL1iQh0D3AlH6QqEfjIzOLq2MG0piNCA4f5YUEj3xewPo3FnCqFK',null,null,to_date('06-SEP-19','DD-MON-RR'),null,to_date('06-SEP-19','DD-MON-RR'),null);
REM INSERTING into KONSULTACIJE.KORISNICKI_NALOG_ROLA
SET DEFINE OFF;
Insert into KONSULTACIJE.KORISNICKI_NALOG_ROLA (KORISNICKI_NALOG_ID,ROLA_ID) values (284,2);
Insert into KONSULTACIJE.KORISNICKI_NALOG_ROLA (KORISNICKI_NALOG_ID,ROLA_ID) values (285,2);
Insert into KONSULTACIJE.KORISNICKI_NALOG_ROLA (KORISNICKI_NALOG_ID,ROLA_ID) values (286,2);
REM INSERTING into KONSULTACIJE.NASTAVNIK
SET DEFINE OFF;
Insert into KONSULTACIJE.NASTAVNIK (JMBG,IME,PREZIME,EMAIL,BROJ_TELEFONA,KABINET,SLIKA) values ('1225652125495','Dusan','Savic','dsavic@fon.bg.ac.rs','0641215569','304','https://vignette.wikia.nocookie.net/fantendo/images/6/6e/Small-mario.png');
Insert into KONSULTACIJE.NASTAVNIK (JMBG,IME,PREZIME,EMAIL,BROJ_TELEFONA,KABINET,SLIKA) values ('2222222222222','Milos','Milic','mmilic@gmail.com','0615665655','B006','https://vignette.wikia.nocookie.net/fantendo/images/6/6e/Small-mario.png');
Insert into KONSULTACIJE.NASTAVNIK (JMBG,IME,PREZIME,EMAIL,BROJ_TELEFONA,KABINET,SLIKA) values ('3333333333333','Ilija','Antonic','iantonic@gmail.com','0612233365','C103','https://vignette.wikia.nocookie.net/fantendo/images/6/6e/Small-mario.png');
Insert into KONSULTACIJE.NASTAVNIK (JMBG,IME,PREZIME,EMAIL,BROJ_TELEFONA,KABINET,SLIKA) values ('4444444444444','Sasa','Lazarevic','sslazarevic@fon.bg.ac.rs','0611223666','B108',null);
Insert into KONSULTACIJE.NASTAVNIK (JMBG,IME,PREZIME,EMAIL,BROJ_TELEFONA,KABINET,SLIKA) values ('5555555555555','Vojislav','Stanojevic','vstanojevic@fon.bg.ac.rs','064122236','104',null);
Insert into KONSULTACIJE.NASTAVNIK (JMBG,IME,PREZIME,EMAIL,BROJ_TELEFONA,KABINET,SLIKA) values ('6666666666666','Sinisa','Vlajic','ssvlajic@fon.bg.ac.rs','06447745541','105',null);
REM INSERTING into KONSULTACIJE.POKRIVENOST_NASTAVE
SET DEFINE OFF;
REM INSERTING into KONSULTACIJE.PREDMET
SET DEFINE OFF;
Insert into KONSULTACIJE.PREDMET (ID_PREDMETA,NAZIV,ESPB_BODOVI,GODINA_STUDIJA) values (1,'Softverski paterni',4,'4');
REM INSERTING into KONSULTACIJE.PRILOG
SET DEFINE OFF;
REM INSERTING into KONSULTACIJE.ROLA
SET DEFINE OFF;
Insert into KONSULTACIJE.ROLA (ID_ROLE,NAZIV_ROLE) values (1,'ROLE_NASTAVNIK');
Insert into KONSULTACIJE.ROLA (ID_ROLE,NAZIV_ROLE) values (2,'ROLE_STUDENT');
REM INSERTING into KONSULTACIJE.SKOLSKA_GODINA
SET DEFINE OFF;
Insert into KONSULTACIJE.SKOLSKA_GODINA (ID_SKOLSKE_GODINE,SKOLSKA_GODINA,SEMESTAR) values (1,'2018/19','zimski');
Insert into KONSULTACIJE.SKOLSKA_GODINA (ID_SKOLSKE_GODINE,SKOLSKA_GODINA,SEMESTAR) values (2,'2018/19','letnji');
REM INSERTING into KONSULTACIJE.STUDENT
SET DEFINE OFF;
Insert into KONSULTACIJE.STUDENT (BROJ_INDEKSA,IME,PREZIME,GODINA_UPISA,SMER,BROJ_TELEFONA,EMAIL) values ('2014/0044','Dane','Nikolic',2014,'ISIT','066291195','danen1995@gmail.com');
Insert into KONSULTACIJE.STUDENT (BROJ_INDEKSA,IME,PREZIME,GODINA_UPISA,SMER,BROJ_TELEFONA,EMAIL) values ('2014/0041','Milan','Milanovic',2014,'ISIT','0658775195','milan@gmail.com');
Insert into KONSULTACIJE.STUDENT (BROJ_INDEKSA,IME,PREZIME,GODINA_UPISA,SMER,BROJ_TELEFONA,EMAIL) values ('2014/0045','Dordje','Milisevic',2014,'MGMT','066222554','djole@gmail.com');
Insert into KONSULTACIJE.STUDENT (BROJ_INDEKSA,IME,PREZIME,GODINA_UPISA,SMER,BROJ_TELEFONA,EMAIL) values ('2014/0042','Marko','Antic',2014,'ISIT','0605950413','markoantic@gmail.com');
Insert into KONSULTACIJE.STUDENT (BROJ_INDEKSA,IME,PREZIME,GODINA_UPISA,SMER,BROJ_TELEFONA,EMAIL) values ('2014/0043','Zorana','Ikonic',2014,'ISIT','0611222333','zorana@gmail.com');
Insert into KONSULTACIJE.STUDENT (BROJ_INDEKSA,IME,PREZIME,GODINA_UPISA,SMER,BROJ_TELEFONA,EMAIL) values ('2014/0103','Slavko','Nikolic',2014,'MGMT','0617007605','sslavko@gmail.com');
Insert into KONSULTACIJE.STUDENT (BROJ_INDEKSA,IME,PREZIME,GODINA_UPISA,SMER,BROJ_TELEFONA,EMAIL) values ('2014/0333','?????','???????',2014,'????','0617007607','?????');
Insert into KONSULTACIJE.STUDENT (BROJ_INDEKSA,IME,PREZIME,GODINA_UPISA,SMER,BROJ_TELEFONA,EMAIL) values ('2014/0037','Milica','Kostic',2014,'pravni','0616768039','milica.kostic.pi@gmail.com');
REM INSERTING into KONSULTACIJE.STUDENT_KONSULTACIJE
SET DEFINE OFF;
REM INSERTING into KONSULTACIJE.TIP_DOGADJAJA
SET DEFINE OFF;
Insert into KONSULTACIJE.TIP_DOGADJAJA (ID_TIPA_DOGADJAJA,NAZIV_TIPA_DOGADJAJA) values (1,'Clanstvo komisije');
Insert into KONSULTACIJE.TIP_DOGADJAJA (ID_TIPA_DOGADJAJA,NAZIV_TIPA_DOGADJAJA) values (2,'Konsultacije');
Insert into KONSULTACIJE.TIP_DOGADJAJA (ID_TIPA_DOGADJAJA,NAZIV_TIPA_DOGADJAJA) values (3,'Nastava');
--------------------------------------------------------
--  DDL for Index NASTAVNIK_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KONSULTACIJE"."NASTAVNIK_PK" ON "KONSULTACIJE"."NASTAVNIK" ("JMBG") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index KORISNICKI_NALOG_UK3
--------------------------------------------------------

  CREATE UNIQUE INDEX "KONSULTACIJE"."KORISNICKI_NALOG_UK3" ON "KONSULTACIJE"."KORISNICKI_NALOG" ("BROJ_INDEKSA_STUDENTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PREDMET_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KONSULTACIJE"."PREDMET_PK" ON "KONSULTACIJE"."PREDMET" ("ID_PREDMETA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ROLA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KONSULTACIJE"."ROLA_PK" ON "KONSULTACIJE"."ROLA" ("ID_ROLE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index DOGADJAJ_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KONSULTACIJE"."DOGADJAJ_PK" ON "KONSULTACIJE"."DOGADJAJ" ("ID_KALENDARA", "ID_DOGADJAJA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index KORISNICKI_NALOG_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "KONSULTACIJE"."KORISNICKI_NALOG_UK1" ON "KONSULTACIJE"."KORISNICKI_NALOG" ("KORISNICKO_IME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index STUDENT_KONSULTACIJE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KONSULTACIJE"."STUDENT_KONSULTACIJE_PK" ON "KONSULTACIJE"."STUDENT_KONSULTACIJE" ("ID_KALENDARA", "ID_DOGADJAJA", "BROJ_INDEKSA_STUDENTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index KALENDAR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KONSULTACIJE"."KALENDAR_PK" ON "KONSULTACIJE"."KALENDAR" ("ID_KALENDARA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index KORISNICKI_NALOG_ROLA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KONSULTACIJE"."KORISNICKI_NALOG_ROLA_PK" ON "KONSULTACIJE"."KORISNICKI_NALOG_ROLA" ("KORISNICKI_NALOG_ID", "ROLA_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index STUDENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KONSULTACIJE"."STUDENT_PK" ON "KONSULTACIJE"."STUDENT" ("BROJ_INDEKSA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SKOLSKA_GODINA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KONSULTACIJE"."SKOLSKA_GODINA_PK" ON "KONSULTACIJE"."SKOLSKA_GODINA" ("ID_SKOLSKE_GODINE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index KORISNICKI_NALOG_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KONSULTACIJE"."KORISNICKI_NALOG_PK" ON "KONSULTACIJE"."KORISNICKI_NALOG" ("ID_KOR_NAL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index KORISNICKI_NALOG_UK2
--------------------------------------------------------

  CREATE UNIQUE INDEX "KONSULTACIJE"."KORISNICKI_NALOG_UK2" ON "KONSULTACIJE"."KORISNICKI_NALOG" ("JMBG_NASTAVNIKA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index POKRIVENOST_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KONSULTACIJE"."POKRIVENOST_PK" ON "KONSULTACIJE"."POKRIVENOST_NASTAVE" ("JMBG_NASTAVNIKA", "ID_PREDMETA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PRILOG_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KONSULTACIJE"."PRILOG_PK" ON "KONSULTACIJE"."PRILOG" ("ID_PRILOGA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TIP_DOGADJAJA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KONSULTACIJE"."TIP_DOGADJAJA_PK" ON "KONSULTACIJE"."TIP_DOGADJAJA" ("ID_TIPA_DOGADJAJA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger A
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "KONSULTACIJE"."A" 
   before insert on "DOGADJAJ" 
   for each row 
begin  
   if inserting then 
      if :NEW."ID_DOGADJAJA" is null then 
         select DOGADJAJ_SEQ.nextval into :NEW."ID_DOGADJAJA" from dual; 
      end if; 
   end if; 
end;




/
ALTER TRIGGER "KONSULTACIJE"."A" ENABLE;
--------------------------------------------------------
--  DDL for Trigger DOGADJAJ_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "KONSULTACIJE"."DOGADJAJ_TRG" 
BEFORE INSERT ON DOGADJAJ 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_DOGADJAJA IS NULL THEN
      SELECT DOGADJAJ_SEQ.NEXTVAL INTO :NEW.ID_DOGADJAJA FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;



/
ALTER TRIGGER "KONSULTACIJE"."DOGADJAJ_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger DOGADJAJ_TRG1
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "KONSULTACIJE"."DOGADJAJ_TRG1" 
BEFORE INSERT ON DOGADJAJ 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;



/
ALTER TRIGGER "KONSULTACIJE"."DOGADJAJ_TRG1" ENABLE;
--------------------------------------------------------
--  DDL for Trigger DOGADJAJ_TRG2
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "KONSULTACIJE"."DOGADJAJ_TRG2" 
BEFORE INSERT ON DOGADJAJ 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;



/
ALTER TRIGGER "KONSULTACIJE"."DOGADJAJ_TRG2" ENABLE;
--------------------------------------------------------
--  DDL for Trigger KALENDAR_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "KONSULTACIJE"."KALENDAR_TRG" 
BEFORE INSERT ON KALENDAR 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_KALENDARA IS NULL THEN
      SELECT KALENDAR_SEQ.NEXTVAL INTO :NEW.ID_KALENDARA FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;



/
ALTER TRIGGER "KONSULTACIJE"."KALENDAR_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger KORISNICKI_NALOG_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "KONSULTACIJE"."KORISNICKI_NALOG_TRG" 
BEFORE INSERT ON KORISNICKI_NALOG 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;



/
ALTER TRIGGER "KONSULTACIJE"."KORISNICKI_NALOG_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger KORISNICKI_NALOG_TRG1
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "KONSULTACIJE"."KORISNICKI_NALOG_TRG1" 
BEFORE INSERT ON KORISNICKI_NALOG 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "KONSULTACIJE"."KORISNICKI_NALOG_TRG1" ENABLE;
--------------------------------------------------------
--  DDL for Trigger NASTAVNIK_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "KONSULTACIJE"."NASTAVNIK_TRG" 
BEFORE INSERT ON NASTAVNIK 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;



/
ALTER TRIGGER "KONSULTACIJE"."NASTAVNIK_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger POKRIVENOST_NASTAVE_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "KONSULTACIJE"."POKRIVENOST_NASTAVE_TRG" 
BEFORE INSERT ON POKRIVENOST_NASTAVE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;



/
ALTER TRIGGER "KONSULTACIJE"."POKRIVENOST_NASTAVE_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PREDMET_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "KONSULTACIJE"."PREDMET_TRG" 
BEFORE INSERT ON PREDMET 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_PREDMETA IS NULL THEN
      SELECT PREDMET_SEQ.NEXTVAL INTO :NEW.ID_PREDMETA FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;



/
ALTER TRIGGER "KONSULTACIJE"."PREDMET_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PRILOG_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "KONSULTACIJE"."PRILOG_TRG" 
BEFORE INSERT ON PRILOG 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_PRILOGA IS NULL THEN
      SELECT PRILOG_SEQ1.NEXTVAL INTO :NEW.ID_PRILOGA FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;


/
ALTER TRIGGER "KONSULTACIJE"."PRILOG_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PRILOG_TRG1
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "KONSULTACIJE"."PRILOG_TRG1" 
BEFORE INSERT ON PRILOG 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;


/
ALTER TRIGGER "KONSULTACIJE"."PRILOG_TRG1" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SKOLSKA_GODINA_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "KONSULTACIJE"."SKOLSKA_GODINA_TRG" 
BEFORE INSERT ON SKOLSKA_GODINA 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_SKOLSKE_GODINE IS NULL THEN
      SELECT SKOLSKA_GODINA_SEQ.NEXTVAL INTO :NEW.ID_SKOLSKE_GODINE FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;



/
ALTER TRIGGER "KONSULTACIJE"."SKOLSKA_GODINA_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TIP_DOGADJAJA_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "KONSULTACIJE"."TIP_DOGADJAJA_TRG" 
BEFORE INSERT ON TIP_DOGADJAJA 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_TIPA_DOGADJAJA IS NULL THEN
      SELECT TIP_DOGADJAJA_SEQ.NEXTVAL INTO :NEW.ID_TIPA_DOGADJAJA FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;



/
ALTER TRIGGER "KONSULTACIJE"."TIP_DOGADJAJA_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TN_KORISNICKI_NALOG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "KONSULTACIJE"."TN_KORISNICKI_NALOG" 
   before insert on "KONSULTACIJE"."KORISNICKI_NALOG" 
   for each row 
begin  
   if inserting then 
      if :NEW."ID_KOR_NAL" is null then 
         select KORISNICKI_NALOG_SEQ.nextval into :NEW."ID_KOR_NAL" from dual; 
      end if; 
   end if; 
end;

/
ALTER TRIGGER "KONSULTACIJE"."TN_KORISNICKI_NALOG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TN_ROLA
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "KONSULTACIJE"."TN_ROLA" 
   before insert on "ROLA" 
   for each row 
begin  
   if inserting then 
      if :NEW."ID_ROLE" is null then 
         select ROLA_SEQ.nextval into :NEW."ID_ROLE" from dual; 
      end if; 
   end if; 
end;


/
ALTER TRIGGER "KONSULTACIJE"."TN_ROLA" ENABLE;
--------------------------------------------------------
--  Constraints for Table KALENDAR
--------------------------------------------------------

  ALTER TABLE "KONSULTACIJE"."KALENDAR" MODIFY ("ID_KALENDARA" NOT NULL ENABLE);
  ALTER TABLE "KONSULTACIJE"."KALENDAR" ADD CONSTRAINT "KALENDAR_PK" PRIMARY KEY ("ID_KALENDARA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table KORISNICKI_NALOG_ROLA
--------------------------------------------------------

  ALTER TABLE "KONSULTACIJE"."KORISNICKI_NALOG_ROLA" MODIFY ("KORISNICKI_NALOG_ID" NOT NULL ENABLE);
  ALTER TABLE "KONSULTACIJE"."KORISNICKI_NALOG_ROLA" MODIFY ("ROLA_ID" NOT NULL ENABLE);
  ALTER TABLE "KONSULTACIJE"."KORISNICKI_NALOG_ROLA" ADD CONSTRAINT "KORISNICKI_NALOG_ROLA_PK" PRIMARY KEY ("KORISNICKI_NALOG_ID", "ROLA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SKOLSKA_GODINA
--------------------------------------------------------

  ALTER TABLE "KONSULTACIJE"."SKOLSKA_GODINA" MODIFY ("ID_SKOLSKE_GODINE" NOT NULL ENABLE);
  ALTER TABLE "KONSULTACIJE"."SKOLSKA_GODINA" ADD CONSTRAINT "SKOLSKA_GODINA_PK" PRIMARY KEY ("ID_SKOLSKE_GODINE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table KORISNICKI_NALOG
--------------------------------------------------------

  ALTER TABLE "KONSULTACIJE"."KORISNICKI_NALOG" ADD CONSTRAINT "KORISNICKI_NALOG_UK3" UNIQUE ("BROJ_INDEKSA_STUDENTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "KONSULTACIJE"."KORISNICKI_NALOG" ADD CONSTRAINT "KORISNICKI_NALOG_UK2" UNIQUE ("JMBG_NASTAVNIKA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "KONSULTACIJE"."KORISNICKI_NALOG" MODIFY ("KORISNICKO_IME" NOT NULL ENABLE);
  ALTER TABLE "KONSULTACIJE"."KORISNICKI_NALOG" ADD CONSTRAINT "KORISNICKI_NALOG_UK1" UNIQUE ("KORISNICKO_IME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "KONSULTACIJE"."KORISNICKI_NALOG" MODIFY ("ID_KOR_NAL" NOT NULL ENABLE);
  ALTER TABLE "KONSULTACIJE"."KORISNICKI_NALOG" ADD CONSTRAINT "KORISNICKI_NALOG_PK" PRIMARY KEY ("ID_KOR_NAL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TIP_DOGADJAJA
--------------------------------------------------------

  ALTER TABLE "KONSULTACIJE"."TIP_DOGADJAJA" MODIFY ("ID_TIPA_DOGADJAJA" NOT NULL ENABLE);
  ALTER TABLE "KONSULTACIJE"."TIP_DOGADJAJA" ADD CONSTRAINT "TIP_DOGADJAJA_PK" PRIMARY KEY ("ID_TIPA_DOGADJAJA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table POKRIVENOST_NASTAVE
--------------------------------------------------------

  ALTER TABLE "KONSULTACIJE"."POKRIVENOST_NASTAVE" MODIFY ("JMBG_NASTAVNIKA" NOT NULL ENABLE);
  ALTER TABLE "KONSULTACIJE"."POKRIVENOST_NASTAVE" MODIFY ("ID_PREDMETA" NOT NULL ENABLE);
  ALTER TABLE "KONSULTACIJE"."POKRIVENOST_NASTAVE" ADD CONSTRAINT "POKRIVENOST_PK" PRIMARY KEY ("JMBG_NASTAVNIKA", "ID_PREDMETA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PREDMET
--------------------------------------------------------

  ALTER TABLE "KONSULTACIJE"."PREDMET" MODIFY ("ID_PREDMETA" NOT NULL ENABLE);
  ALTER TABLE "KONSULTACIJE"."PREDMET" ADD CONSTRAINT "PREDMET_PK" PRIMARY KEY ("ID_PREDMETA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table STUDENT_KONSULTACIJE
--------------------------------------------------------

  ALTER TABLE "KONSULTACIJE"."STUDENT_KONSULTACIJE" MODIFY ("ID_KALENDARA" NOT NULL ENABLE);
  ALTER TABLE "KONSULTACIJE"."STUDENT_KONSULTACIJE" MODIFY ("ID_DOGADJAJA" NOT NULL ENABLE);
  ALTER TABLE "KONSULTACIJE"."STUDENT_KONSULTACIJE" MODIFY ("BROJ_INDEKSA_STUDENTA" NOT NULL ENABLE);
  ALTER TABLE "KONSULTACIJE"."STUDENT_KONSULTACIJE" ADD CONSTRAINT "STUDENT_KONSULTACIJE_PK" PRIMARY KEY ("ID_KALENDARA", "ID_DOGADJAJA", "BROJ_INDEKSA_STUDENTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ROLA
--------------------------------------------------------

  ALTER TABLE "KONSULTACIJE"."ROLA" MODIFY ("ID_ROLE" NOT NULL ENABLE);
  ALTER TABLE "KONSULTACIJE"."ROLA" ADD CONSTRAINT "ROLA_PK" PRIMARY KEY ("ID_ROLE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table STUDENT
--------------------------------------------------------

  ALTER TABLE "KONSULTACIJE"."STUDENT" MODIFY ("BROJ_INDEKSA" NOT NULL ENABLE);
  ALTER TABLE "KONSULTACIJE"."STUDENT" ADD CONSTRAINT "STUDENT_PK" PRIMARY KEY ("BROJ_INDEKSA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DOGADJAJ
--------------------------------------------------------

  ALTER TABLE "KONSULTACIJE"."DOGADJAJ" MODIFY ("ID_KALENDARA" NOT NULL ENABLE);
  ALTER TABLE "KONSULTACIJE"."DOGADJAJ" MODIFY ("ID_DOGADJAJA" NOT NULL ENABLE);
  ALTER TABLE "KONSULTACIJE"."DOGADJAJ" ADD CONSTRAINT "DOGADJAJ_PK" PRIMARY KEY ("ID_KALENDARA", "ID_DOGADJAJA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRILOG
--------------------------------------------------------

  ALTER TABLE "KONSULTACIJE"."PRILOG" MODIFY ("ID_PRILOGA" NOT NULL ENABLE);
  ALTER TABLE "KONSULTACIJE"."PRILOG" ADD CONSTRAINT "PRILOG_PK" PRIMARY KEY ("ID_PRILOGA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table NASTAVNIK
--------------------------------------------------------

  ALTER TABLE "KONSULTACIJE"."NASTAVNIK" MODIFY ("JMBG" NOT NULL ENABLE);
  ALTER TABLE "KONSULTACIJE"."NASTAVNIK" ADD CONSTRAINT "NASTAVNIK_PK" PRIMARY KEY ("JMBG")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DOGADJAJ
--------------------------------------------------------

  ALTER TABLE "KONSULTACIJE"."DOGADJAJ" ADD CONSTRAINT "DOGADJAJ_FK1" FOREIGN KEY ("ID_TIPA_DOGADJAJA")
	  REFERENCES "KONSULTACIJE"."TIP_DOGADJAJA" ("ID_TIPA_DOGADJAJA") ENABLE;
  ALTER TABLE "KONSULTACIJE"."DOGADJAJ" ADD CONSTRAINT "DOGADJAJ_FK2" FOREIGN KEY ("ID_KALENDARA")
	  REFERENCES "KONSULTACIJE"."KALENDAR" ("ID_KALENDARA") ENABLE;
  ALTER TABLE "KONSULTACIJE"."DOGADJAJ" ADD CONSTRAINT "DOGADJAJ_FK3" FOREIGN KEY ("ID_PREDMETA")
	  REFERENCES "KONSULTACIJE"."PREDMET" ("ID_PREDMETA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table KALENDAR
--------------------------------------------------------

  ALTER TABLE "KONSULTACIJE"."KALENDAR" ADD CONSTRAINT "KALENDAR_FK1" FOREIGN KEY ("ID_SKOLSKE_GODINE")
	  REFERENCES "KONSULTACIJE"."SKOLSKA_GODINA" ("ID_SKOLSKE_GODINE") ENABLE;
  ALTER TABLE "KONSULTACIJE"."KALENDAR" ADD CONSTRAINT "KALENDAR_FK2" FOREIGN KEY ("JMBG_NASTAVNIKA")
	  REFERENCES "KONSULTACIJE"."NASTAVNIK" ("JMBG") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table KORISNICKI_NALOG
--------------------------------------------------------

  ALTER TABLE "KONSULTACIJE"."KORISNICKI_NALOG" ADD CONSTRAINT "KORISNICKI_NALOG_FK1" FOREIGN KEY ("JMBG_NASTAVNIKA")
	  REFERENCES "KONSULTACIJE"."NASTAVNIK" ("JMBG") ENABLE;
  ALTER TABLE "KONSULTACIJE"."KORISNICKI_NALOG" ADD CONSTRAINT "KORISNICKI_NALOG_FK2" FOREIGN KEY ("BROJ_INDEKSA_STUDENTA")
	  REFERENCES "KONSULTACIJE"."STUDENT" ("BROJ_INDEKSA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table KORISNICKI_NALOG_ROLA
--------------------------------------------------------

  ALTER TABLE "KONSULTACIJE"."KORISNICKI_NALOG_ROLA" ADD CONSTRAINT "KORISNICKI_NALOG_ROLA_FK1" FOREIGN KEY ("KORISNICKI_NALOG_ID")
	  REFERENCES "KONSULTACIJE"."KORISNICKI_NALOG" ("ID_KOR_NAL") ENABLE;
  ALTER TABLE "KONSULTACIJE"."KORISNICKI_NALOG_ROLA" ADD CONSTRAINT "KORISNICKI_NALOG_ROLA_FK2" FOREIGN KEY ("ROLA_ID")
	  REFERENCES "KONSULTACIJE"."ROLA" ("ID_ROLE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table POKRIVENOST_NASTAVE
--------------------------------------------------------

  ALTER TABLE "KONSULTACIJE"."POKRIVENOST_NASTAVE" ADD CONSTRAINT "POKRIVENOST_FK1" FOREIGN KEY ("JMBG_NASTAVNIKA")
	  REFERENCES "KONSULTACIJE"."NASTAVNIK" ("JMBG") ENABLE;
  ALTER TABLE "KONSULTACIJE"."POKRIVENOST_NASTAVE" ADD CONSTRAINT "POKRIVENOST_FK2" FOREIGN KEY ("ID_PREDMETA")
	  REFERENCES "KONSULTACIJE"."PREDMET" ("ID_PREDMETA") ENABLE;
  ALTER TABLE "KONSULTACIJE"."POKRIVENOST_NASTAVE" ADD CONSTRAINT "POKRIVENOST_FK3" FOREIGN KEY ("ID_SKOLSKE_GODINE")
	  REFERENCES "KONSULTACIJE"."SKOLSKA_GODINA" ("ID_SKOLSKE_GODINE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRILOG
--------------------------------------------------------

  ALTER TABLE "KONSULTACIJE"."PRILOG" ADD CONSTRAINT "PRILOG_FK1" FOREIGN KEY ("ID_KALENDARA", "ID_DOGADJAJA", "BROJ_INDEKSA_STUDENTA")
	  REFERENCES "KONSULTACIJE"."STUDENT_KONSULTACIJE" ("ID_KALENDARA", "ID_DOGADJAJA", "BROJ_INDEKSA_STUDENTA") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table STUDENT_KONSULTACIJE
--------------------------------------------------------

  ALTER TABLE "KONSULTACIJE"."STUDENT_KONSULTACIJE" ADD CONSTRAINT "STUDENT_KONSULTACIJE_FK1" FOREIGN KEY ("ID_KALENDARA", "ID_DOGADJAJA")
	  REFERENCES "KONSULTACIJE"."DOGADJAJ" ("ID_KALENDARA", "ID_DOGADJAJA") ENABLE;
  ALTER TABLE "KONSULTACIJE"."STUDENT_KONSULTACIJE" ADD CONSTRAINT "STUDENT_KONSULTACIJE_FK2" FOREIGN KEY ("BROJ_INDEKSA_STUDENTA")
	  REFERENCES "KONSULTACIJE"."STUDENT" ("BROJ_INDEKSA") ENABLE;
