--------------------------------------------------------
--  File created - Tuesday-October-22-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence DOGADJAJ_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "DOGADJAJ_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 341 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence KALENDAR_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "KALENDAR_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence KORISNICKI_NALOG_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "KORISNICKI_NALOG_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 341 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence NASTAVNIK_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "NASTAVNIK_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence PREDMET_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PREDMET_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence PRILOG_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PRILOG_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 81 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence PRILOG_SEQ1
--------------------------------------------------------

   CREATE SEQUENCE  "PRILOG_SEQ1"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ROLA_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ROLA_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 ORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SKOLSKA_GODINA_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SKOLSKA_GODINA_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence TIP_DOGADJAJA_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "TIP_DOGADJAJA_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table ATTACHMENT
--------------------------------------------------------

  CREATE TABLE "ATTACHMENT" 
   (	"ATTACHMENT_ID" NUMBER, 
	"NAME" VARCHAR2(20 BYTE), 
	"EVENT_ID" NUMBER, 
	"CALENDAR_ID" NUMBER, 
	"INDEX_NUMBER" VARCHAR2(20 BYTE), 
	"LOCATION" BLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("LOCATION") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table CALENDAR
--------------------------------------------------------

  CREATE TABLE "CALENDAR" 
   (	"CALENDAR_ID" NUMBER, 
	"SCHOOL_YEAR_ID" NUMBER, 
	"TEACHER_ID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table COVERAGE
--------------------------------------------------------

  CREATE TABLE "COVERAGE" 
   (	"TEACHER_ID" VARCHAR2(13 BYTE), 
	"SUBJECT_ID" NUMBER, 
	"FUNCTION" VARCHAR2(20 BYTE), 
	"SCHOOL_YEAR_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EVENT
--------------------------------------------------------

  CREATE TABLE "EVENT" 
   (	"CALENDAR_ID" NUMBER, 
	"EVENT_ID" NUMBER, 
	"START_DATE_TIME" DATE, 
	"END_DATE_TIME" DATE, 
	"PLACE" VARCHAR2(50 BYTE), 
	"EVENT_TYPE_ID" NUMBER, 
	"EVENT_LEVEL" VARCHAR2(20 BYTE), 
	"FUNCTION" VARCHAR2(50 BYTE), 
	"CANDIDATE" VARCHAR2(50 BYTE), 
	"TOPIC" VARCHAR2(50 BYTE), 
	"CAPACITY" NUMBER, 
	"NUMBER_OF_SCHEDULED_CONS" NUMBER, 
	"COURSE_FUNCTION" VARCHAR2(20 BYTE), 
	"SUBJECT_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EVENT_TYPE
--------------------------------------------------------

  CREATE TABLE "EVENT_TYPE" 
   (	"EVENT_TYPE_ID" NUMBER, 
	"NAME" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ROLE
--------------------------------------------------------

  CREATE TABLE "ROLE" 
   (	"ROLE_ID" NUMBER, 
	"ROLE_NAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SCHEDULED_CONSULTATION
--------------------------------------------------------

  CREATE TABLE "SCHEDULED_CONSULTATION" 
   (	"CALENDAR_ID" NUMBER, 
	"EVENT_ID" NUMBER, 
	"INDEX_NUMBER" VARCHAR2(20 BYTE), 
	"STATUS" VARCHAR2(200 BYTE), 
	"TITLE" VARCHAR2(200 BYTE), 
	"DESCRIPTION" VARCHAR2(1000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SCHOOL_YEAR
--------------------------------------------------------

  CREATE TABLE "SCHOOL_YEAR" 
   (	"SCHOOL_YEAR_ID" NUMBER, 
	"SCHOOL_YEAR" VARCHAR2(20 BYTE), 
	"SEMESTER" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table STUDENT
--------------------------------------------------------

  CREATE TABLE "STUDENT" 
   (	"INDEX_NUMBER" VARCHAR2(10 BYTE), 
	"FIRST_NAME" VARCHAR2(20 BYTE), 
	"LAST_NAME" VARCHAR2(20 BYTE), 
	"YEAR_OF_ENTRY" NUMBER(4,0), 
	"DEPARTMENT" VARCHAR2(100 BYTE), 
	"TELEPHONE" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SUBJECT
--------------------------------------------------------

  CREATE TABLE "SUBJECT" 
   (	"SUBJECT_ID" NUMBER, 
	"NAME" VARCHAR2(100 BYTE), 
	"ESPB" NUMBER, 
	"YEAR_OF_STUDIES" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TEACHER
--------------------------------------------------------

  CREATE TABLE "TEACHER" 
   (	"TEACHER_ID" VARCHAR2(13 BYTE), 
	"FIRST_NAME" VARCHAR2(20 BYTE), 
	"LAST_NAME" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"TELEPHONE" VARCHAR2(20 BYTE), 
	"CABINET" VARCHAR2(20 BYTE), 
	"IMAGE" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table USER_ACCOUNT
--------------------------------------------------------

  CREATE TABLE "USER_ACCOUNT" 
   (	"USER_ACCOUNT_ID" NUMBER, 
	"USER_NAME" VARCHAR2(30 BYTE), 
	"PASSWORD" VARCHAR2(60 BYTE), 
	"TEACHER_ID" VARCHAR2(13 BYTE), 
	"INDEX_NUMBER" VARCHAR2(20 BYTE), 
	"CREATED_AT" DATE, 
	"CREATED_BY" NUMBER, 
	"UPDATED_AT" DATE, 
	"UPDATED_BY" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table USER_ACCOUNT_ROLE
--------------------------------------------------------

  CREATE TABLE "USER_ACCOUNT_ROLE" 
   (	"USER_ACCOUNT_ID" NUMBER, 
	"ROLE_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into ATTACHMENT
SET DEFINE OFF;
REM INSERTING into CALENDAR
SET DEFINE OFF;
Insert into CALENDAR (CALENDAR_ID,SCHOOL_YEAR_ID,TEACHER_ID) values (1,1,'1225652125495');
REM INSERTING into COVERAGE
SET DEFINE OFF;
REM INSERTING into EVENT
SET DEFINE OFF;
Insert into EVENT (CALENDAR_ID,EVENT_ID,START_DATE_TIME,END_DATE_TIME,PLACE,EVENT_TYPE_ID,EVENT_LEVEL,FUNCTION,CANDIDATE,TOPIC,CAPACITY,NUMBER_OF_SCHEDULED_CONS,COURSE_FUNCTION,SUBJECT_ID) values (1,321,null,null,null,2,null,null,null,null,null,null,null,null);
Insert into EVENT (CALENDAR_ID,EVENT_ID,START_DATE_TIME,END_DATE_TIME,PLACE,EVENT_TYPE_ID,EVENT_LEVEL,FUNCTION,CANDIDATE,TOPIC,CAPACITY,NUMBER_OF_SCHEDULED_CONS,COURSE_FUNCTION,SUBJECT_ID) values (1,1,null,null,null,2,null,null,null,null,null,null,null,null);
Insert into EVENT (CALENDAR_ID,EVENT_ID,START_DATE_TIME,END_DATE_TIME,PLACE,EVENT_TYPE_ID,EVENT_LEVEL,FUNCTION,CANDIDATE,TOPIC,CAPACITY,NUMBER_OF_SCHEDULED_CONS,COURSE_FUNCTION,SUBJECT_ID) values (1,2,null,null,null,2,null,null,null,null,null,null,null,null);
REM INSERTING into EVENT_TYPE
SET DEFINE OFF;
Insert into EVENT_TYPE (EVENT_TYPE_ID,NAME) values (1,'Commision membership');
Insert into EVENT_TYPE (EVENT_TYPE_ID,NAME) values (2,'Consultation');
Insert into EVENT_TYPE (EVENT_TYPE_ID,NAME) values (3,'Course');
REM INSERTING into ROLE
SET DEFINE OFF;
Insert into ROLE (ROLE_ID,ROLE_NAME) values (1,'ROLE_TEACHER');
Insert into ROLE (ROLE_ID,ROLE_NAME) values (2,'ROLE_STUDENT');
REM INSERTING into SCHEDULED_CONSULTATION
SET DEFINE OFF;
REM INSERTING into SCHOOL_YEAR
SET DEFINE OFF;
Insert into SCHOOL_YEAR (SCHOOL_YEAR_ID,SCHOOL_YEAR,SEMESTER) values (1,'2018/19','winter');
Insert into SCHOOL_YEAR (SCHOOL_YEAR_ID,SCHOOL_YEAR,SEMESTER) values (2,'2018/19','summer');
REM INSERTING into STUDENT
SET DEFINE OFF;
Insert into STUDENT (INDEX_NUMBER,FIRST_NAME,LAST_NAME,YEAR_OF_ENTRY,DEPARTMENT,TELEPHONE,EMAIL) values ('2014/0044','Dane','Nikolic',2014,'ISIT','066291195','danen1995@gmail.com');
Insert into STUDENT (INDEX_NUMBER,FIRST_NAME,LAST_NAME,YEAR_OF_ENTRY,DEPARTMENT,TELEPHONE,EMAIL) values ('2014/0043','Zorana','Ikonic',2014,'ISIT','0611222333','zorana@gmail.com');
REM INSERTING into SUBJECT
SET DEFINE OFF;
Insert into SUBJECT (SUBJECT_ID,NAME,ESPB,YEAR_OF_STUDIES) values (1,'Softverski paterni',4,'4');
REM INSERTING into TEACHER
SET DEFINE OFF;
Insert into TEACHER (TEACHER_ID,FIRST_NAME,LAST_NAME,EMAIL,TELEPHONE,CABINET,IMAGE) values ('1225652125495','Dusan','Savic','dsavic@fon.bg.ac.rs','0641215569','304','https://vignette.wikia.nocookie.net/fantendo/images/6/6e/Small-mario.png');
REM INSERTING into USER_ACCOUNT
SET DEFINE OFF;
Insert into USER_ACCOUNT (USER_ACCOUNT_ID,USER_NAME,PASSWORD,TEACHER_ID,INDEX_NUMBER,CREATED_AT,CREATED_BY,UPDATED_AT,UPDATED_BY) values (301,'dane','$2a$10$O1VCrR2krOMIp2bAZZJAGeUfxMai0RoYH7mdxs3MzsNz3PJmKlBnu','1225652125495',null,to_date('26-SEP-19','DD-MON-RR'),null,to_date('26-SEP-19','DD-MON-RR'),null);
REM INSERTING into USER_ACCOUNT_ROLE
SET DEFINE OFF;
Insert into USER_ACCOUNT_ROLE (USER_ACCOUNT_ID,ROLE_ID) values (301,1);
--------------------------------------------------------
--  DDL for Index NASTAVNIK_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "NASTAVNIK_PK" ON "TEACHER" ("TEACHER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index KORISNICKI_NALOG_UK3
--------------------------------------------------------

  CREATE UNIQUE INDEX "KORISNICKI_NALOG_UK3" ON "USER_ACCOUNT" ("INDEX_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PREDMET_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PREDMET_PK" ON "SUBJECT" ("SUBJECT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ROLA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ROLA_PK" ON "ROLE" ("ROLE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index DOGADJAJ_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DOGADJAJ_PK" ON "EVENT" ("CALENDAR_ID", "EVENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index KORISNICKI_NALOG_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "KORISNICKI_NALOG_UK1" ON "USER_ACCOUNT" ("USER_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index STUDENT_KONSULTACIJE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "STUDENT_KONSULTACIJE_PK" ON "SCHEDULED_CONSULTATION" ("CALENDAR_ID", "EVENT_ID", "INDEX_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index KALENDAR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KALENDAR_PK" ON "CALENDAR" ("CALENDAR_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index KORISNICKI_NALOG_ROLA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KORISNICKI_NALOG_ROLA_PK" ON "USER_ACCOUNT_ROLE" ("USER_ACCOUNT_ID", "ROLE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index STUDENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "STUDENT_PK" ON "STUDENT" ("INDEX_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SKOLSKA_GODINA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SKOLSKA_GODINA_PK" ON "SCHOOL_YEAR" ("SCHOOL_YEAR_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index KORISNICKI_NALOG_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KORISNICKI_NALOG_PK" ON "USER_ACCOUNT" ("USER_ACCOUNT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index KORISNICKI_NALOG_UK2
--------------------------------------------------------

  CREATE UNIQUE INDEX "KORISNICKI_NALOG_UK2" ON "USER_ACCOUNT" ("TEACHER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index POKRIVENOST_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "POKRIVENOST_PK" ON "COVERAGE" ("TEACHER_ID", "SUBJECT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PRILOG_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRILOG_PK" ON "ATTACHMENT" ("ATTACHMENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TIP_DOGADJAJA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TIP_DOGADJAJA_PK" ON "EVENT_TYPE" ("EVENT_TYPE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger A
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "A" 
   before insert on "EVENT" 
   for each row 
begin  
   if inserting then 
      if :NEW."EVENT_ID" is null then 
         select DOGADJAJ_SEQ.nextval into :NEW."EVENT_ID" from dual; 
      end if; 
   end if; 
end;
/
ALTER TRIGGER "A" ENABLE;
--------------------------------------------------------
--  DDL for Trigger DOGADJAJ_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "DOGADJAJ_TRG" 
BEFORE INSERT ON EVENT 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "DOGADJAJ_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger DOGADJAJ_TRG1
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "DOGADJAJ_TRG1" 
BEFORE INSERT ON EVENT 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "DOGADJAJ_TRG1" ENABLE;
--------------------------------------------------------
--  DDL for Trigger DOGADJAJ_TRG2
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "DOGADJAJ_TRG2" 
BEFORE INSERT ON EVENT 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "DOGADJAJ_TRG2" ENABLE;
--------------------------------------------------------
--  DDL for Trigger KALENDAR_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "KALENDAR_TRG" 
BEFORE INSERT ON CALENDAR 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "KALENDAR_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger KORISNICKI_NALOG_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "KORISNICKI_NALOG_TRG" 
BEFORE INSERT ON USER_ACCOUNT 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "KORISNICKI_NALOG_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger KORISNICKI_NALOG_TRG1
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "KORISNICKI_NALOG_TRG1" 
BEFORE INSERT ON USER_ACCOUNT 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "KORISNICKI_NALOG_TRG1" ENABLE;
--------------------------------------------------------
--  DDL for Trigger NASTAVNIK_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "NASTAVNIK_TRG" 
BEFORE INSERT ON TEACHER 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "NASTAVNIK_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger POKRIVENOST_NASTAVE_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "POKRIVENOST_NASTAVE_TRG" 
BEFORE INSERT ON COVERAGE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "POKRIVENOST_NASTAVE_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PREDMET_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PREDMET_TRG" 
BEFORE INSERT ON SUBJECT 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "PREDMET_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PRILOG_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PRILOG_TRG" 
BEFORE INSERT ON ATTACHMENT 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "PRILOG_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PRILOG_TRG1
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PRILOG_TRG1" 
BEFORE INSERT ON ATTACHMENT 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "PRILOG_TRG1" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SKOLSKA_GODINA_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SKOLSKA_GODINA_TRG" 
BEFORE INSERT ON SCHOOL_YEAR 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SKOLSKA_GODINA_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TIP_DOGADJAJA_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TIP_DOGADJAJA_TRG" 
BEFORE INSERT ON EVENT_TYPE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "TIP_DOGADJAJA_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TN_KORISNICKI_NALOG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TN_KORISNICKI_NALOG" 
   before insert on "USER_ACCOUNT" 
   for each row 
begin  
   if inserting then 
      if :NEW."USER_ACCOUNT_ID" is null then 
         select KORISNICKI_NALOG_SEQ.nextval into :NEW."USER_ACCOUNT_ID" from dual; 
      end if; 
   end if; 
end;
/
ALTER TRIGGER "TN_KORISNICKI_NALOG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TN_ROLA
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TN_ROLA" 
   before insert on "ROLE" 
   for each row 
begin  
   if inserting then 
      if :NEW."ROLE_ID" is null then 
         select ROLA_SEQ.nextval into :NEW."ROLE_ID" from dual; 
      end if; 
   end if; 
end;
/
ALTER TRIGGER "TN_ROLA" ENABLE;
--------------------------------------------------------
--  Constraints for Table SCHEDULED_CONSULTATION
--------------------------------------------------------

  ALTER TABLE "SCHEDULED_CONSULTATION" MODIFY ("CALENDAR_ID" NOT NULL ENABLE);
  ALTER TABLE "SCHEDULED_CONSULTATION" MODIFY ("EVENT_ID" NOT NULL ENABLE);
  ALTER TABLE "SCHEDULED_CONSULTATION" MODIFY ("INDEX_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SCHEDULED_CONSULTATION" ADD CONSTRAINT "STUDENT_KONSULTACIJE_PK" PRIMARY KEY ("CALENDAR_ID", "EVENT_ID", "INDEX_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EVENT_TYPE
--------------------------------------------------------

  ALTER TABLE "EVENT_TYPE" MODIFY ("EVENT_TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "EVENT_TYPE" ADD CONSTRAINT "TIP_DOGADJAJA_PK" PRIMARY KEY ("EVENT_TYPE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table COVERAGE
--------------------------------------------------------

  ALTER TABLE "COVERAGE" MODIFY ("TEACHER_ID" NOT NULL ENABLE);
  ALTER TABLE "COVERAGE" MODIFY ("SUBJECT_ID" NOT NULL ENABLE);
  ALTER TABLE "COVERAGE" ADD CONSTRAINT "POKRIVENOST_PK" PRIMARY KEY ("TEACHER_ID", "SUBJECT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CALENDAR
--------------------------------------------------------

  ALTER TABLE "CALENDAR" MODIFY ("CALENDAR_ID" NOT NULL ENABLE);
  ALTER TABLE "CALENDAR" ADD CONSTRAINT "KALENDAR_PK" PRIMARY KEY ("CALENDAR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TEACHER
--------------------------------------------------------

  ALTER TABLE "TEACHER" MODIFY ("TEACHER_ID" NOT NULL ENABLE);
  ALTER TABLE "TEACHER" ADD CONSTRAINT "NASTAVNIK_PK" PRIMARY KEY ("TEACHER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USER_ACCOUNT_ROLE
--------------------------------------------------------

  ALTER TABLE "USER_ACCOUNT_ROLE" MODIFY ("USER_ACCOUNT_ID" NOT NULL ENABLE);
  ALTER TABLE "USER_ACCOUNT_ROLE" MODIFY ("ROLE_ID" NOT NULL ENABLE);
  ALTER TABLE "USER_ACCOUNT_ROLE" ADD CONSTRAINT "KORISNICKI_NALOG_ROLA_PK" PRIMARY KEY ("USER_ACCOUNT_ID", "ROLE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SUBJECT
--------------------------------------------------------

  ALTER TABLE "SUBJECT" MODIFY ("SUBJECT_ID" NOT NULL ENABLE);
  ALTER TABLE "SUBJECT" ADD CONSTRAINT "PREDMET_PK" PRIMARY KEY ("SUBJECT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SCHOOL_YEAR
--------------------------------------------------------

  ALTER TABLE "SCHOOL_YEAR" MODIFY ("SCHOOL_YEAR_ID" NOT NULL ENABLE);
  ALTER TABLE "SCHOOL_YEAR" ADD CONSTRAINT "SKOLSKA_GODINA_PK" PRIMARY KEY ("SCHOOL_YEAR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ROLE
--------------------------------------------------------

  ALTER TABLE "ROLE" MODIFY ("ROLE_ID" NOT NULL ENABLE);
  ALTER TABLE "ROLE" ADD CONSTRAINT "ROLA_PK" PRIMARY KEY ("ROLE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USER_ACCOUNT
--------------------------------------------------------

  ALTER TABLE "USER_ACCOUNT" ADD CONSTRAINT "KORISNICKI_NALOG_UK3" UNIQUE ("INDEX_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "USER_ACCOUNT" ADD CONSTRAINT "KORISNICKI_NALOG_UK2" UNIQUE ("TEACHER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "USER_ACCOUNT" MODIFY ("USER_NAME" NOT NULL ENABLE);
  ALTER TABLE "USER_ACCOUNT" ADD CONSTRAINT "KORISNICKI_NALOG_UK1" UNIQUE ("USER_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "USER_ACCOUNT" MODIFY ("USER_ACCOUNT_ID" NOT NULL ENABLE);
  ALTER TABLE "USER_ACCOUNT" ADD CONSTRAINT "KORISNICKI_NALOG_PK" PRIMARY KEY ("USER_ACCOUNT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EVENT
--------------------------------------------------------

  ALTER TABLE "EVENT" MODIFY ("EVENT_TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "EVENT" MODIFY ("CALENDAR_ID" NOT NULL ENABLE);
  ALTER TABLE "EVENT" MODIFY ("EVENT_ID" NOT NULL ENABLE);
  ALTER TABLE "EVENT" ADD CONSTRAINT "DOGADJAJ_PK" PRIMARY KEY ("CALENDAR_ID", "EVENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table STUDENT
--------------------------------------------------------

  ALTER TABLE "STUDENT" MODIFY ("INDEX_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "STUDENT" ADD CONSTRAINT "STUDENT_PK" PRIMARY KEY ("INDEX_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ATTACHMENT
--------------------------------------------------------

  ALTER TABLE "ATTACHMENT" MODIFY ("ATTACHMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "ATTACHMENT" ADD CONSTRAINT "PRILOG_PK" PRIMARY KEY ("ATTACHMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ATTACHMENT
--------------------------------------------------------

  ALTER TABLE "ATTACHMENT" ADD CONSTRAINT "PRILOG_FK1" FOREIGN KEY ("CALENDAR_ID", "EVENT_ID", "INDEX_NUMBER")
	  REFERENCES "SCHEDULED_CONSULTATION" ("CALENDAR_ID", "EVENT_ID", "INDEX_NUMBER") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CALENDAR
--------------------------------------------------------

  ALTER TABLE "CALENDAR" ADD CONSTRAINT "KALENDAR_FK1" FOREIGN KEY ("SCHOOL_YEAR_ID")
	  REFERENCES "SCHOOL_YEAR" ("SCHOOL_YEAR_ID") ENABLE;
  ALTER TABLE "CALENDAR" ADD CONSTRAINT "KALENDAR_FK2" FOREIGN KEY ("TEACHER_ID")
	  REFERENCES "TEACHER" ("TEACHER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COVERAGE
--------------------------------------------------------

  ALTER TABLE "COVERAGE" ADD CONSTRAINT "POKRIVENOST_FK1" FOREIGN KEY ("TEACHER_ID")
	  REFERENCES "TEACHER" ("TEACHER_ID") ENABLE;
  ALTER TABLE "COVERAGE" ADD CONSTRAINT "POKRIVENOST_FK2" FOREIGN KEY ("SUBJECT_ID")
	  REFERENCES "SUBJECT" ("SUBJECT_ID") ENABLE;
  ALTER TABLE "COVERAGE" ADD CONSTRAINT "POKRIVENOST_FK3" FOREIGN KEY ("SCHOOL_YEAR_ID")
	  REFERENCES "SCHOOL_YEAR" ("SCHOOL_YEAR_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EVENT
--------------------------------------------------------

  ALTER TABLE "EVENT" ADD CONSTRAINT "DOGADJAJ_FK1" FOREIGN KEY ("EVENT_TYPE_ID")
	  REFERENCES "EVENT_TYPE" ("EVENT_TYPE_ID") ENABLE;
  ALTER TABLE "EVENT" ADD CONSTRAINT "DOGADJAJ_FK2" FOREIGN KEY ("CALENDAR_ID")
	  REFERENCES "CALENDAR" ("CALENDAR_ID") ENABLE;
  ALTER TABLE "EVENT" ADD CONSTRAINT "DOGADJAJ_FK3" FOREIGN KEY ("SUBJECT_ID")
	  REFERENCES "SUBJECT" ("SUBJECT_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SCHEDULED_CONSULTATION
--------------------------------------------------------

  ALTER TABLE "SCHEDULED_CONSULTATION" ADD CONSTRAINT "STUDENT_KONSULTACIJE_FK1" FOREIGN KEY ("CALENDAR_ID", "EVENT_ID")
	  REFERENCES "EVENT" ("CALENDAR_ID", "EVENT_ID") ENABLE;
  ALTER TABLE "SCHEDULED_CONSULTATION" ADD CONSTRAINT "STUDENT_KONSULTACIJE_FK2" FOREIGN KEY ("INDEX_NUMBER")
	  REFERENCES "STUDENT" ("INDEX_NUMBER") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USER_ACCOUNT
--------------------------------------------------------

  ALTER TABLE "USER_ACCOUNT" ADD CONSTRAINT "KORISNICKI_NALOG_FK1" FOREIGN KEY ("TEACHER_ID")
	  REFERENCES "TEACHER" ("TEACHER_ID") ENABLE;
  ALTER TABLE "USER_ACCOUNT" ADD CONSTRAINT "KORISNICKI_NALOG_FK2" FOREIGN KEY ("INDEX_NUMBER")
	  REFERENCES "STUDENT" ("INDEX_NUMBER") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USER_ACCOUNT_ROLE
--------------------------------------------------------

  ALTER TABLE "USER_ACCOUNT_ROLE" ADD CONSTRAINT "KORISNICKI_NALOG_ROLA_FK1" FOREIGN KEY ("USER_ACCOUNT_ID")
	  REFERENCES "USER_ACCOUNT" ("USER_ACCOUNT_ID") ENABLE;
  ALTER TABLE "USER_ACCOUNT_ROLE" ADD CONSTRAINT "KORISNICKI_NALOG_ROLA_FK2" FOREIGN KEY ("ROLE_ID")
	  REFERENCES "ROLE" ("ROLE_ID") ENABLE;
